package pipeline

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"pod/pkg/backend"
)

var guidSuffixRegex = regexp.MustCompile(`\s*\([0-9a-fA-F-]{6,}\)$`)

func EnsureABSIgnore(dir string) error {
	ignorePath := filepath.Join(dir, ".absignore")
	content := "# Ignore patterns generated by pod\n*.precut\n*.bak\n*.tmp*\n*.lock\n.work/\n"
	if _, err := os.Stat(ignorePath); os.IsNotExist(err) {
		return os.WriteFile(ignorePath, []byte(content), 0644)
	}
	return nil
}

func ParseABSEpisodePublishedAt(ep *backend.Episode) int64 {
	if ep == nil {
		return 0
	}
	if ep.PublishedAt > 0 {
		return ep.PublishedAt
	}
	if ep.PubDate != "" {
		formats := []string{
			time.RFC1123,
			time.RFC1123Z,
			time.RFC3339,
			time.RFC822,
			time.RFC822Z,
			"2006-01-02 15:04:05",
			"2006-01-02T15:04:05.000Z",
			"2006-01-02",
		}
		for _, f := range formats {
			if t, err := time.Parse(f, strings.TrimSpace(ep.PubDate)); err == nil {
				return t.UnixMilli()
			}
		}
	}
	return 0
}

func NormalizeEpisodeTitle(name string) string {
	base := strings.TrimSuffix(name, ".mp3")
	base = guidSuffixRegex.ReplaceAllString(base, "")
	return strings.ToLower(strings.TrimSpace(base))
}

func quarantineFile(path string) error {
	if _, err := os.Stat(path); err != nil {
		return nil
	}
	bakPath := path + ".bak"
	return os.Rename(path, bakPath)
}

func QuarantineAbandonedDuplicates(podDir string, trackedEpisodes []backend.Episode) []string {
	var quarantined []string

	trackedByNormalized := make(map[string]string)
	trackedFiles := make(map[string]bool)

	for _, ep := range trackedEpisodes {
		fn := ""
		if ep.AudioFile != nil && ep.AudioFile.Metadata != nil && ep.AudioFile.Metadata.Filename != "" {
			fn = ep.AudioFile.Metadata.Filename
		} else if ep.Title != "" {
			fn = ep.Title + ".mp3"
		}
		if fn != "" {
			trackedFiles[fn] = true
			norm := NormalizeEpisodeTitle(fn)
			trackedByNormalized[norm] = fn
		}
	}

	mp3Files, err := filepath.Glob(filepath.Join(podDir, "*.mp3"))
	if err != nil {
		return nil
	}

	for _, mp3 := range mp3Files {
		fn := filepath.Base(mp3)
		if strings.HasSuffix(fn, ".bak") {
			continue
		}

		if trackedFiles[fn] {
			continue
		}

		norm := NormalizeEpisodeTitle(fn)
		if trackedFn, exists := trackedByNormalized[norm]; exists && trackedFn != fn {
			trackedPath := filepath.Join(podDir, trackedFn)
			if fi, err := os.Stat(trackedPath); err != nil || fi.IsDir() || fi.Size() == 0 {
				continue
			}
			base := strings.TrimSuffix(mp3, ".mp3")

			if err := quarantineFile(mp3); err == nil {
				_ = quarantineFile(base + ".cuts.json")
				_ = quarantineFile(base + ".transcript.json")
				_ = quarantineFile(mp3 + ".precut")
				_ = quarantineFile(base + ".srt")
				_ = quarantineFile(base + ".txt")

				quarantined = append(quarantined, fn)
			}
		}
	}

	if len(quarantined) > 0 {
		if err := EnsureABSIgnore(podDir); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to ensure .absignore in '%s': %v\n", podDir, err)
		}
	}

	return quarantined
}

// FormatQuarantinedSummary renders the result of QuarantineAbandonedDuplicates
// for display, returning "" when nothing was quarantined. It returns the text
// rather than printing it: the TUI is a caller, and writing to stdout from
// under a full-screen UI corrupts the display.
func FormatQuarantinedSummary(quarantined []string, podName string) string {
	if len(quarantined) == 0 {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "Quarantined %d abandoned duplicate(s) in '%s' to .bak:\n", len(quarantined), podName)
	for _, q := range quarantined {
		fmt.Fprintf(&b, "  - %s -> %s.bak\n", q, q)
	}
	return b.String()
}
